### ISSUE TITLE
Crashes if terminal is too small

### ISSUE THREAD

**Issue by rcusw** [rozza368/immersion-tracker#1]
The terminal window must be larger in width than the standard 80 characters when starting the program otherwise curses will return an error when trying to print the help message.

example:
```
Traceback (most recent call last):
                                    File "main.py", line 244, in <module>
                                                                             select_show()
             File "main.py", line 138, in select_show
                                                         print_help_bar(stdscr, ("NAVIGATE", "SELECT", "NEW", "RENAME", "DELETE", "QUIT"))
                                                             File "main.py", line 59, in print_help_bar
                            win.addstr(win_height - 1, 0, f"{help_text:^{win_width-1}}", curses.A_BOLD)
                        _curses.error: addwstr() returned ERR
```

**Comment by rcusw** [comment]
will also crash if shows/episodes list is too long

**Comment by rcusw** [comment]
Fixed in recent commit
